// src/components/ExplanationCard.js — FINAL FULL UPDATE WITH STRIPE + LOADING + ERRORS + PAID FEATURES (December 30, 2025)
// ✅ Multi-page support
// ✅ Vibrant number highlighting
// ✅ Itemized line highlighting
// ✅ Professional PDF
// ✅ PaidFeatures integration
// ✅ Stripe upgrade CTA with loading/error handling
// ✅ Global loading & error states
// ✅ All previous design preserved

import React, { useMemo, useState } from "react";
import jsPDF from "jspdf";
import PaidFeatures from "./PaidFeatures";
import StripeCheckoutButton from "./StripeCheckoutButton";

export default function ExplanationCard({ result, onAnalyzeAnother, isProcessing = false, processingError = null }) {
  const [showExplanation, setShowExplanation] = useState(true);
  const [showNextSteps, setShowNextSteps] = useState(true);
  const [showRawText, setShowRawText] = useState(false);
  const [showHelp, setShowHelp] = useState(false);
  const [activePage, setActivePage] = useState(0);
  const [showFutureTools, setShowFutureTools] = useState(false);

  const safe = useMemo(() => {
    // Handle backend error
    if (result?.error || processingError) {
      return {
        hasError: true,
        errorMessage: result?.error || processingError || "An unknown error occurred.",
      };
    }

    if (!result || !result.pages || result.pages.length === 0) {
      return { hasError: true, errorMessage: "No result data available." };
    }

    const pages = result.pages;
    const currentPage = pages[activePage] || {};
    const structured = currentPage.structured || {};
    const keyAmounts = structured.keyAmounts || {};
    const entries = Object.values(keyAmounts).filter((f) => f && f.label);

    return {
      pages,
      currentPage,
      entries,
      summary: structured.summary || "Your bill has been analyzed.",
      explanation: structured.explanation || "See breakdown below.",
      nextSteps: structured.nextSteps || [],
      rawText: currentPage.rawText || "",
      totalPages: pages.length,
      paidFeatures: result.paidFeatures || null, // From overcharge detection, etc.
      isPaid: result.isPaid || false,
    };
  }, [result, activePage, processingError]);

  const downloadPDF = () => {
    const doc = new jsPDF();
    let y = 20;

    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Medical Bill Summary Report", 20, y);
    y += 10;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text("Generated by ExplainMyBill — Educational Tool", 20, y);
    y += 8;
    doc.text(
      "Date: " + new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }),
      20,
      y
    );
    y += 15;

    doc.setDrawColor(200);
    doc.setLineWidth(0.5);
    doc.line(20, y - 5, 190, y - 5);
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text("This report is for informational purposes only and is not medical, legal, or billing advice.", 20, y);
    doc.text("Always verify all amounts directly with your healthcare provider and insurance company.", 20, y + 6);
    y += 20;

    doc.setTextColor(0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Key Amounts", 20, y);
    y += 12;

    doc.setFontSize(13);
    doc.setFont("helvetica", "normal");

    safe.entries.forEach((field) => {
      doc.setFont("helvetica", "bold");
      doc.text(field.label + ":", 30, y);
      doc.setFont("helvetica", "normal");
      doc.text(field.value, 120, y);
      y += 12;
    });

    y += 10;

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Summary in Plain English", 20, y);
    y += 12;

    doc.setFontSize(12);
    const summaryLines = doc.splitTextToSize(safe.summary, 170);
    doc.text(summaryLines, 20, y);
    y += summaryLines.length * 7 + 10;

    const explanationLines = doc.splitTextToSize(safe.explanation, 170);
    doc.text(explanationLines, 20, y);
    y += explanationLines.length * 7 + 15;

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Recommended Next Steps", 20, y);
    y += 12;

    doc.setFontSize(12);
    safe.nextSteps.forEach((step, i) => {
      doc.text(`${i + 1}. ${step}`, 25, y);
      y += 10;
    });

    if (safe.rawText) {
      y += 15;
      doc.setFontSize(10);
      doc.setTextColor(120);
      doc.text("Excerpt from extracted document text (Page 1):", 20, y);
      y += 8;
      const excerpt = safe.rawText.slice(0, 1000) + (safe.rawText.length > 1000 ? "..." : "");
      const excerptLines = doc.splitTextToSize(excerpt, 170);
      doc.setFontSize(9);
      doc.text(excerptLines, 20, y);
    }

    doc.setDrawColor(200);
    doc.line(20, y + 20, 190, y + 20);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("ExplainMyBill is not affiliated with any healthcare provider or insurer.", 20, y + 30);
    doc.text("This tool is not HIPAA-certified and should not replace official statements.", 20, y + 36);

    doc.save("ExplainMyBill_Professional_Report.pdf");
  };

  const getStyle = (c) => {
    const pct = Math.round((c || 0) * 100);
    if (pct >= 85) return { color: "#10b981", label: "High confidence" };
    if (pct >= 60) return { color: "#f59e0b", label: "Moderate confidence" };
    return { color: "#ef4444", label: "Low confidence — double-check" };
  };

  const highlightNumbers = (text) => {
    if (!text) return null;
    return text.split(/(\$[0-9,]+\.?\d*)/g).map((part, i) => {
      if (/^\$[0-9,]+\.?\d*$/.test(part)) {
        return (
          <span
            key={i}
            className="font-black text-4xl bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 bg-clip-text text-transparent animate-pulse"
          >
            {part}
          </span>
        );
      }
      return <span key={i}>{part}</span>;
    });
  };

  const highlightItemizedLines = (rawText) => {
    if (!rawText || safe.entries.length === 0) return rawText;

    let highlighted = rawText;
    safe.entries.forEach((field) => {
      if (field.citations) {
        field.citations.forEach((c) => {
          const escaped = c.text.trim().replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
          const regex = new RegExp(`(${escaped})`, "gi");
          highlighted = highlighted.replace(
            regex,
            '<mark class="bg-yellow-200 px-2 py-1 rounded font-semibold">$1</mark>'
          );
        });
      }
    });

    return highlighted;
  };

  // === GLOBAL PROCESSING STATES ===
  if (isProcessing) {
    return (
      <div className="max-w-4xl mx-auto p-8 flex flex-col items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-24 w-24 border-t-8 border-b-8 border-indigo-600 mb-8"></div>
        <h2 className="text-4xl font-bold text-indigo-700 mb-4">Analyzing Your Bill...</h2>
        <p className="text-xl text-gray-600 text-center max-w-lg">
          We're carefully reading your document with dual AI models and evidence checking. This usually takes 15–30 seconds.
        </p>
      </div>
    );
  }

  if (safe.hasError) {
    return (
      <div className="max-w-4xl mx-auto p-8">
        <div className="bg-red-50 border-l-8 border-red-600 rounded-3xl p-12 shadow-2xl text-center">
          <h2 className="text-4xl font-black text-red-800 mb-6">Processing Error</h2>
          <p className="text-2xl text-red-700 mb-8">{safe.errorMessage}</p>
          <button
            onClick={onAnalyzeAnother || (() => window.location.reload())}
            className="px-10 py-5 bg-red-600 text-white text-xl font-bold rounded-2xl hover:bg-red-700 transition"
          >
            Try Again
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto p-4 space-y-8">
      {/* Header */}
      <div className="rounded-3xl bg-gradient-to-br from-indigo-600 to-pink-600 p-1 shadow-2xl">
        <div className="bg-white rounded-[26px] p-8">
          <div className="flex flex-col md:flex-row justify-between items-start gap-6">
            <div>
              <h1 className="text-4xl font-black bg-gradient-to-r from-indigo-600 to-pink-600 bg-clip-text text-transparent">
                Your Bill Explained
              </h1>
              <p className="text-gray-600 mt-3 max-w-lg">
                We instantly analyzed your bill with care. Nothing is stored — your privacy is protected.
              </p>
            </div>
            <button
              onClick={onAnalyzeAnother || (() => window.location.reload())}
              className="inline-flex items-center gap-2 bg-white border-2 border-indigo-600 text-indigo-600 px-5 py-2.5 rounded-full font-bold text-base hover:bg-indigo-50 transition"
            >
              <span className="text-lg">←</span>
              Analyze Another Bill
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-10">
            <div className="flex items-center gap-5 bg-gradient-to-br from-emerald-100 to-green-100 px-8 py-7 rounded-3xl shadow-2xl border-4 border-emerald-400">
              <div className="w-16 h-16 bg-gradient-to-br from-emerald-600 to-green-700 rounded-full flex items-center justify-center text-white text-4xl font-black shadow-2xl">
                ✓
              </div>
              <span className="font-black text-gray-800 text-xl">No account needed</span>
            </div>
            <div className="flex items-center gap-5 bg-gradient-to-br from-emerald-100 to-green-100 px-8 py-7 rounded-3xl shadow-2xl border-4 border-emerald-400">
              <div className="w-16 h-16 bg-gradient-to-br from-emerald-600 to-green-700 rounded-full flex items-center justify-center text-white text-4xl font-black shadow-2xl">
                ✓
              </div>
              <span className="font-black text-gray-800 text-xl">Deleted instantly</span>
            </div>
            <div className="flex items-center gap-5 bg-gradient-to-br from-emerald-100 to-green-100 px-8 py-7 rounded-3xl shadow-2xl border-4 border-emerald-400">
              <div className="w-16 h-16 bg-gradient-to-br from-emerald-600 to-green-700 rounded-full flex items-center justify-center text-white text-4xl font-black shadow-2xl">
                ✓
              </div>
              <span className="font-black text-gray-800 text-xl">Clear evidence shown</span>
            </div>
          </div>

          <div className="flex flex-wrap gap-4 items-center mt-8">
            <button
              onClick={() => setShowHelp(true)}
              className="text-indigo-600 font-medium underline hover:no-underline"
            >
              How confidence works
            </button>
            <button
              onClick={downloadPDF}
              className="inline-flex items-center gap-3 bg-gradient-to-r from-indigo-700 to-purple-700 text-white px-8 py-4 rounded-2xl font-bold shadow-2xl hover:shadow-3xl transition-all"
            >
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                />
              </svg>
              Download Professional Report (PDF)
            </button>
          </div>
        </div>
      </div>

      {/* Multi-page navigation */}
      {safe.totalPages > 1 && (
        <div className="flex justify-center items-center gap-4 py-4">
          <button
            onClick={() => setActivePage(Math.max(0, activePage - 1))}
            disabled={activePage === 0}
            className="px-6 py-3 bg-indigo-100 rounded-xl font-medium disabled:opacity-50 hover:bg-indigo-200 transition"
          >
            ← Previous Page
          </button>
          <span className="font-bold text-xl text-indigo-700">
            Page {activePage + 1} of {safe.totalPages}
          </span>
          <button
            onClick={() => setActivePage(Math.min(safe.totalPages - 1, activePage + 1))}
            disabled={activePage === safe.totalPages - 1}
            className="px-6 py-3 bg-indigo-100 rounded-xl font-medium disabled:opacity-50 hover:bg-indigo-200 transition"
          >
            Next Page →
          </button>
        </div>
      )}

      {/* Key Amount Cards */}
      <div className="grid md:grid-cols-3 gap-6">
        {safe.entries.map((field) => {
          const style = getStyle(field.confidence);
          const pct = Math.round((field.confidence || 0) * 100);

          return (
            <div
              key={field.label}
              className="bg-white rounded-2xl shadow-lg p-6 border-t-4"
              style={{ borderTopColor: style.color }}
            >
              <h3 className="text-lg font-semibold text-gray-700 mb-2">{field.label}</h3>
              <p className="text-4xl font-black text-gray-900 mb-6">{field.value}</p>

              <div className="space-y-4">
                <div>
                  <div className="flex justify-between mb-1">
                    <span className="text-sm text-gray-600">Confidence</span>
                    <span className="font-bold text-gray-900">{pct}%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-3">
                    <div
                      className="h-3 rounded-full transition-all duration-700"
                      style={{ width: `${pct}%`, backgroundColor: style.color }}
                    />
                  </div>
                  <p className="text-sm font-medium text-gray-700 mt-2">{style.label}</p>
                </div>

                {field.citations?.length > 0 && (
                  <div className="bg-gray-50 rounded-xl p-4">
                    <p className="text-sm font-medium text-gray-700 mb-2">Found on these lines:</p>
                    <ul className="space-y-1 text-xs text-gray-600">
                      {field.citations.slice(0, 3).map((c, i) => (
                        <li key={i} className="font-mono bg-white px-3 py-1 rounded border">
                          Line {c.line}: “…{c.text.trim()}…”
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* Plain English Summary */}
      <div className="bg-white rounded-2xl shadow-lg overflow-hidden">
        <button
          onClick={() => setShowExplanation(!showExplanation)}
          className="w-full px-8 py-5 flex justify-between items-center hover:bg-gray-50 transition"
        >
          <h2 className="text-2xl font-bold text-gray-900">Plain English Summary</h2>
          <span className="text-3xl text-gray-400 font-light">{showExplanation ? "−" : "+"}</span>
        </button>

        {showExplanation && (
          <div className="px-8 pb-8 pt-4 space-y-6">
            <p className="text-lg text-gray-700 leading-relaxed">{safe.summary}</p>

            <div className="bg-gradient-to-r from-indigo-50 to-purple-50 border-l-4 border-indigo-500 p-6 rounded-r-xl">
              <p className="text-lg text-gray-800 leading-loose">{highlightNumbers(safe.explanation)}</p>
            </div>
          </div>
        )}
      </div>

      {/* Next Steps */}
      <div className="bg-white rounded-2xl shadow-lg overflow-hidden">
        <button
          onClick={() => setShowNextSteps(!showNextSteps)}
          className="w-full px-8 py-5 flex justify-between items-center hover:bg-gray-50 transition"
        >
          <h2 className="text-2xl font-bold text-gray-900">Next Steps</h2>
          <span className="text-3xl text-gray-400 font-light">{showNextSteps ? "−" : "+"}</span>
        </button>

        {showNextSteps && (
          <div className="px-8 pb-8 pt-4 space-y-5">
            {safe.nextSteps.map((step, i) => (
              <div
                key={i}
                className="flex items-center gap-5 p-5 bg-gradient-to-r from-indigo-50 to-pink-50 rounded-xl border border-indigo-100"
              >
                <div className="flex-shrink-0 w-10 h-10 bg-gradient-to-br from-indigo-600 to-pink-600 text-white rounded-full flex items-center justify-center text-xl font-bold shadow-md">
                  {i + 1}
                </div>
                <p className="text-gray-800 leading-relaxed flex-1">{step}</p>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* PAID FEATURES FROM BACKEND */}
      <PaidFeatures features={safe.paidFeatures} />

      {/* PREMIUM UPGRADE CTA (only if not paid) */}
      {!safe.isPaid && !safe.paidFeatures && (
        <div className="bg-gradient-to-r from-purple-100 to-pink-100 rounded-3xl p-12 text-center border-4 border-purple-300 shadow-2xl">
          <h3 className="text-5xl font-black text-purple-800 mb-6">
            Unlock Premium Power Tools
          </h3>
          <p className="text-2xl text-gray-700 mb-10 max-w-3xl mx-auto">
            Get red flag alerts, estimated savings, EOB comparison, professional appeal letters, overcharge detection, and more.
          </p>
          <StripeCheckoutButton
            priceId={process.env.REACT_APP_STRIPE_PRICE_MONTHLY || "price_test_monthly"}
            label="Upgrade Now – $19.99/month"
          />
          <p className="text-lg text-gray-600 mt-8">
            Cancel anytime • Instant access • 100% privacy protected
          </p>
        </div>
      )}

      {/* Future Insurance Claim Tools */}
      <div className="bg-gradient-to-r from-purple-50 to-indigo-50 rounded-3xl p-8 border-2 border-purple-300">
        <button
          onClick={() => setShowFutureTools(!showFutureTools)}
          className="w-full flex justify-between items-center text-left"
        >
          <h2 className="text-3xl font-black text-purple-800">
            🚀 Coming Soon: Insurance Claim Power Tools
          </h2>
          <span className="text-4xl text-purple-400">{showFutureTools ? "−" : "+"}</span>
        </button>

        {showFutureTools && (
          <div className="mt-8 grid md:grid-cols-2 gap-8">
            <div className="bg-white rounded-2xl p-6 shadow-xl border border-purple-200">
              <h3 className="text-xl font-bold text-purple-700 mb-3">EOB Comparison Tool</h3>
              <p className="text-gray-700">
                Upload your provider bill + insurance EOB → instantly spot discrepancies, overcharges, or missing adjustments.
              </p>
            </div>
            <div className="bg-white rounded-2xl p-6 shadow-xl border border-purple-200">
              <h3 className="text-xl font-bold text-purple-700 mb-3">Appeal Letter Generator</h3>
              <p className="text-gray-700">
                Auto-generates professional appeal letters with evidence citations — ready to send to your insurer.
              </p>
            </div>
            <div className="bg-white rounded-2xl p-6 shadow-xl border border-purple-200">
              <h3 className="text-xl font-bold text-purple-700 mb-3">Overcharge Detector</h3>
              <p className="text-gray-700">
                Compares your charges to Medicare and FAIR Health averages — flags potential overbilling.
              </p>
            </div>
            <div className="bg-white rounded-2xl p-6 shadow-xl border border-purple-200">
              <h3 className="text-xl font-bold text-purple-700 mb-3">Prior Auth Tracker</h3>
              <p className="text-gray-700">
                Track pre-approvals, deadlines, and status — never miss a prior authorization again.
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Raw Text with Highlighting */}
      <div className="bg-gray-100 rounded-2xl p-6">
        <button
          onClick={() => setShowRawText(!showRawText)}
          className="text-indigo-600 font-semibold hover:underline"
        >
          {showRawText ? "← Hide extracted text" : "Show full extracted text (with evidence highlighted)"}
        </button>

        {showRawText && (
          <pre
            className="mt-4 p-6 bg-white rounded-xl text-sm text-gray-700 overflow-x-auto border"
            dangerouslySetInnerHTML={{
              __html: highlightItemizedLines(safe.rawText) || "No raw text available.",
            }}
          />
        )}
      </div>

      {/* Confidence Help Modal */}
      {showHelp && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full p-8">
            <h3 className="text-2xl font-bold mb-6">Confidence Explained</h3>
            <div className="space-y-5">
              <div className="flex items-center gap-4">
                <div className="w-8 h-8 bg-emerald-500 rounded-full"></div>
                <div>
                  <strong>High (85%+)</strong>
                  <p className="text-sm text-gray-600">Clear label and exact match</p>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <div className="w-8 h-8 bg-amber-500 rounded-full"></div>
                <div>
                  <strong>Moderate (60–84%)</strong>
                  <p className="text-sm text-gray-600">Good but from image scan</p>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <div className="w-8 h-8 bg-red-500 rounded-full"></div>
                <div>
                  <strong>Low (&lt;60%)</strong>
                  <p className="text-sm text-gray-600">Uncertain — always verify</p>
                </div>
              </div>
            </div>
            <button
              onClick={() => setShowHelp(false)}
              className="mt-8 w-full bg-gradient-to-r from-indigo-600 to-pink-600 text-white py-3 rounded-xl font-bold"
            >
              Got it!
            </button>
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="text-center text-gray-500 text-sm mt-12">
        <p>Educational tool • Not medical/legal advice • Not HIPAA-certified</p>
        <p className="mt-1">Always confirm with your provider before paying.</p>
      </div>
    </div>
  );
}
